### ISSUE TITLE
支持ubuntu22.04安装吗？centos7快过时了

### ISSUE THREAD

**Issue by opcache** [opendevops-cn/opendevops#127]
支持ubuntu22.04安装吗？

**Comment by ss1917** [comment]
https://github.com/opendevops-cn/codo-deploy-docs                目前文档是根据 Rocky Linux 9 编写的

**Comment by cyancow** [comment]
> 支持ubuntu22.04安装吗？

@opcache 1.0已经不在进行迭代，当前最新版本2.0，经过部署测试，Ubuntu16,18,20支持，22没进行测试，理论上是没问题的。
