### ISSUE TITLE
代码会开源吗？

### ISSUE THREAD

**Issue by shaohk** [opendevops-cn/opendevops#13]
如题

**Comment by yanghongfei** [comment]
代码已经是开源的了，请详细看下文档，
我们采用的是微服务设计，每个服务单独模块，单独运行的，开发的时候不限语言，只要是标准API都可以接入。
- 前端代码：[codo](https://github.com/opendevops-cn/codo)
- 管理后端：[codo-admin](https://github.com/opendevops-cn/codo-admin)
- 定时任务：[codo-cron](https://github.com/opendevops-cn/codo-cron)
- 任务调度：[codo-task](https://github.com/opendevops-cn/codo-task)
- 资产管理：[codo-cmdb](https://github.com/opendevops-cn/codo-cmdb)
- 配置中心：[codo-kerrigan](https://github.com/opendevops-cn/kerrigan)
- 运维工具：[codo-tools](https://github.com/opendevops-cn/codo-tools)
- 域名管理：[codo-dns](https://github.com/opendevops-cn/codo-dns)

**Comment by shaohk** [comment]
> 代码已经是开源的了，请详细看下文档，
> 我们采用的是微服务设计，每个服务单独模块，单独运行的，开发的时候不限语言，只要是标准API都可以接入。
> 
> * 前端代码：[codo](https://github.com/opendevops-cn/codo)
> * 管理后端：[codo-admin](https://github.com/opendevops-cn/codo-admin)
> * 定时任务：[codo-cron](https://github.com/opendevops-cn/codo-cron)
> * 任务调度：[codo-task](https://github.com/opendevops-cn/codo-task)
> * 资产管理：[codo-cmdb](https://github.com/opendevops-cn/codo-cmdb)
> * 配置中心：[codo-kerrigan](https://github.com/opendevops-cn/kerrigan)
> * 运维工具：[codo-tools](https://github.com/opendevops-cn/codo-tools)
> * 域名管理：[codo-dns](https://github.com/opendevops-cn/codo-dns)

感谢哈，早上用手机看的，没看全

还有个请教的地方，就是cmdb里面内网服务器，包括机房、机柜、柜上位置等信息的管理吗？

**Comment by yanghongfei** [comment]
> > 代码已经是开源的了，请详细看下文档，
> > 我们采用的是微服务设计，每个服务单独模块，单独运行的，开发的时候不限语言，只要是标准API都可以接入。
> > 
> > * 前端代码：[codo](https://github.com/opendevops-cn/codo)
> > * 管理后端：[codo-admin](https://github.com/opendevops-cn/codo-admin)
> > * 定时任务：[codo-cron](https://github.com/opendevops-cn/codo-cron)
> > * 任务调度：[codo-task](https://github.com/opendevops-cn/codo-task)
> > * 资产管理：[codo-cmdb](https://github.com/opendevops-cn/codo-cmdb)
> > * 配置中心：[codo-kerrigan](https://github.com/opendevops-cn/kerrigan)
> > * 运维工具：[codo-tools](https://github.com/opendevops-cn/codo-tools)
> > * 域名管理：[codo-dns](https://github.com/opendevops-cn/codo-dns)
> 
> 感谢哈，早上用手机看的，没看全
> 
> 还有个请教的地方，就是cmdb里面内网服务器，包括机房、机柜、柜上位置等信息的管理吗？

目前设计的字段很多都是考虑到共用的，现在有的字段支持IDC分类，像你说的机柜，位置，这个一般是没办法自动获取到的，想加这2个字段其实也很简单，CMDB设计的是主表和信息表分离的，扩展字段稍微改一下代码，就好了，后续看需求是否支持这些，另外，我们CMDB支持从AWS/阿里云/腾讯云上自动获取到主机信息，对于哪些有几百台的完全不用担心，直接一键帮你全拉下来。

**Comment by shaohk** [comment]
> > > 代码已经是开源的了，请详细看下文档，
> > > 我们采用的是微服务设计，每个服务单独模块，单独运行的，开发的时候不限语言，只要是标准API都可以接入。
> > > 
> > > * 前端代码：[codo](https://github.com/opendevops-cn/codo)
> > > * 管理后端：[codo-admin](https://github.com/opendevops-cn/codo-admin)
> > > * 定时任务：[codo-cron](https://github.com/opendevops-cn/codo-cron)
> > > * 任务调度：[codo-task](https://github.com/opendevops-cn/codo-task)
> > > * 资产管理：[codo-cmdb](https://github.com/opendevops-cn/codo-cmdb)
> > > * 配置中心：[codo-kerrigan](https://github.com/opendevops-cn/kerrigan)
> > > * 运维工具：[codo-tools](https://github.com/opendevops-cn/codo-tools)
> > > * 域名管理：[codo-dns](https://github.com/opendevops-cn/codo-dns)
> > 
> > 
> > 感谢哈，早上用手机看的，没看全
> > 还有个请教的地方，就是cmdb里面内网服务器，包括机房、机柜、柜上位置等信息的管理吗？
> 
> 目前设计的字段很多都是考虑到共用的，现在有的字段支持IDC分类，像你说的机柜，位置，这个一般是没办法自动获取到的，想加这2个字段其实也很简单，CMDB设计的是主表和信息表分离的，扩展字段稍微改一下代码，就好了，后续看需求是否支持这些，另外，我们CMDB支持从AWS/阿里云/腾讯云上自动获取到主机信息，对于哪些有几百台的完全不用担心，直接一键帮你全拉下来。

get it, thanks!
