### ISSUE TITLE
目前没有发现任何一个模块是完整可以跑通的。心累

### ISSUE THREAD

**Issue by xlliu** [opendevops-cn/opendevops#22]
半个月了，目前没有发现任何一个模块是完整可以跑通的。心累

**Comment by xlliu** [comment]
开源的版本和 文档/视频的版本差别太大，几乎所有功能都是没有办法使用的，代码功能块缺失太严重了。 
二次开发慎重，自己重新写一套比二次开发这个成本要低

**Comment by ss1917** [comment]
代码一直在迭代，文档也一直在跟进。因为环境和网络条件的不确定，在部署使用中遇到问题 请加群沟通  群号：18252156

**Comment by xlliu** [comment]
模块功能后端返回的响应都是假的， 后端响应的全是成功
去后端看逻辑，是代码逻辑缺失

**Comment by xlliu** [comment]
可能是没有完成的功能也在页面上挂出来了，误导了
