### ISSUE TITLE
FQA 中 Docker内部的MySQL、Redis无法连接问题 描述有问题 

### ISSUE THREAD

**Issue by coolfish-a** [opendevops-cn/opendevops#41]
![image](https://user-images.githubusercontent.com/17448955/70677604-9e1e9f80-1cca-11ea-85d7-2933bb4742c2.png)
这个 /var/www/codo-admin/db_sync.py 是容器内部文件，你截图描述为 从宿主机上查看，而且从宿主机 ping容器ip 也不会ping通 

另：
搭建时，在此出错
[root@localhost codo-cmdb]# docker exec -ti codocmdb_codo_cmdb_1 /usr/local/bin/python3 /var/www/codo-cmdb/db_sync.py
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.223' ([Errno 110] Connection timed out)")
我通过清理iptables -F 后，此问题仍然存在，请问如何解决？

**Comment by ss1917** [comment]
172.16.0.223 这是谁的地址？？？  你不检查下配置吗

**Comment by coolfish-a** [comment]
谢谢提醒，这一步是在mysql数据库中创建表，数据库已经创建成功，我进入mysql容器查看ip并不是这个地址172.16.0.223，mysql容器地址查看：/etc/hosts 是172.17.0.5  请问该如何排查这种问题？

**Comment by coolfish-a** [comment]
https://github.com/opendevops-cn/opendevops/issues/41#issuecomment-564823912  查到问题原因了，是我修改脚本未正常执行，谢谢！
