### ISSUE TITLE
任务系统部署报错

### ISSUE THREAD

**Issue by leon0204** [opendevops-cn/opendevops#60]
/root/.pm2/logs/codo-task-exec-task-error-16.log last 15 lines:
16|codo-ta | 2020-04-20 11:14 +08:00:     super(BlockingConnection, self)._handle_read()
16|codo-ta | 2020-04-20 11:14 +08:00:   File "/usr/local/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 343, in _handle_read
16|codo-ta | 2020-04-20 11:14 +08:00:     return self._handle_error(error)
16|codo-ta | 2020-04-20 11:14 +08:00:   File "/usr/local/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 302, in _handle_error
16|codo-ta | 2020-04-20 11:14 +08:00:     self._handle_disconnect()
16|codo-ta | 2020-04-20 11:14 +08:00:   File "/usr/local/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 248, in _handle_disconnect
16|codo-ta | 2020-04-20 11:14 +08:00:     self._adapter_disconnect()
16|codo-ta | 2020-04-20 11:14 +08:00:   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 318, in _adapter_disconnect
16|codo-ta | 2020-04-20 11:14 +08:00:     self._check_state_on_disconnect()
16|codo-ta | 2020-04-20 11:14 +08:00:   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 368, in _check_state_on_disconnect
16|codo-ta | 2020-04-20 11:14 +08:00:     super(BlockingConnection, self)._check_state_on_disconnect()
16|codo-ta | 2020-04-20 11:14 +08:00:   File "/usr/local/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 153, in _check_state_on_disconnect
16|codo-ta | 2020-04-20 11:14 +08:00:     raise exceptions.ProbableAuthenticationError
16|codo-ta | 2020-04-20 11:14 +08:00: pika.exceptions.ProbableAuthenticationError
16|codo-ta | 2020-04-20 11:14 +08:00: PROGRESS:ki4q6cD4AqM7XTzaRotW3g INFO       2020-04-20 11:14:55,919 logger_key                read_log                       LINE.NO: 67   : xxxx

**Comment by leon0204** [comment]
测试codo-task

#01.日志
tailf /var/log/supervisor/task.log #确认没有报错
这一步检查正确
tailf /var/log/supervisor/exec_task.log
这一步显示没有文件
tailf /var/log/supervisor/task_cron.log
这一步报上面的错误

**Comment by ss1917** [comment]
请确保rabbitMQ 正确部署，请确保配置文件的MQ配置正确，请确保MQ可以连通

**Comment by leon0204** [comment]
mq问题 重启之后配置失效了已解决
