### ISSUE TITLE
关于SVN

### ISSUE THREAD

**Issue by swimmingchar** [opendevops-cn/opendevops#7]
问一下，为什么我看好多都不支持svn发布啊？

**Comment by yanghongfei** [comment]
Git是分布式的，SVN比较简单，相比下来Git功能全，用的人也多。

**Comment by yanghongfei** [comment]
> 问一下，为什么我看好多都不支持SVN发布啊？

如果你想要用SVN发布，同理，SVN也有post commit这种钩子，你同样可以借助我们的任务平台来实现你要做的任务。

**Comment by swimmingchar** [comment]
好的，多谢
