### ISSUE TITLE
codo-admin管理后端部署SQL错误

### ISSUE THREAD

**Issue by fairychao** [opendevops-cn/opendevops#70]
SQL脚本：
INSERT INTO `mg_functions` VALUES (6,'ss','/login/','ALL','10','2018-03-21 10:29:14','2018-03-20 18:35:24'),

数据库表结构：
CREATE TABLE `mg_functions` (
  `func_id` int(11) NOT NULL AUTO_INCREMENT,
  `func_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  _**`app_code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,**_
  `uri` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `method_type` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  _**`parameters` text COLLATE utf8mb4_unicode_ci,**_
  `status` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `utime` datetime DEFAULT NULL,
  `ctime` datetime DEFAULT NULL,
  PRIMARY KEY (`func_id`),
  KEY `ix_mg_functions_method_type` (`method_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

**Comment by xiaoyuan2019** [comment]
把新增的两个字段app_code和parameters都设置为null再进行插入即可

**Comment by zhaophy** [comment]
> SQL脚本：
> INSERT INTO `mg_functions` VALUES (6,'ss','/login/','ALL','10','2018-03-21 10:29:14','2018-03-20 18:35:24'),
> 
> 数据库表结构：
> CREATE TABLE `mg_functions` (
> `func_id` int(11) NOT NULL AUTO_INCREMENT,
> `func_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> _**`app_code` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,**_
> `uri` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> `method_type` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> _**`parameters` text COLLATE utf8mb4_unicode_ci,**_
> `status` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> `utime` datetime DEFAULT NULL,
> `ctime` datetime DEFAULT NULL,
> PRIMARY KEY (`func_id`),
> KEY `ix_mg_functions_method_type` (`method_type`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
hi，did u fix it ?

**Comment by biaopei** [comment]
需要修改SQL语句，把新增的两个字段app_code和parameters都设置为null再进行插入即可。修改后的SQL语句如下
`INSERT INTO `mg_functions`  VALUES  (6,'ss','NULL','/login/','ALL','NULL','10','2018-03-21 10:29:14','2018-03-20 18:35:24'),(9,'管理员','NULL','/','ALL','NULL','0','2018-03-21 14:04:59','2018-03-21 14:04:59'),(10,'任务管理员','NULL','/task/v2/task/','ALL','NULL','0','2019-03-21 10:57:54','2018-03-22 10:09:10'),(12,'修改密码','NULL','/mg/v2/accounts/password/','PATCH','NULL','0','2019-03-21 11:07:20','2018-03-22 16:27:12'),(15,'提交任务','NULL','/task/v2/task/accept/','POST','NULL','0','2019-03-21 10:57:29','2018-06-08 09:26:00'),(16,'获 取CSRF','NULL','/task/v2/task/accept/','GET','NULL','0','2018-12-27 13:16:41','2018-06-08 09:26:51'),(33,'发布配置','NULL','/task/v2/task_other/publish_cd/','GET','NULL','0','2018-12-05 09:59:48','2018-12-05 09:37:24'),(35,'系统用户获取','NULL','/mg/v2/accounts/','GET','NULL','0','2018-12-14 14:44:51','2018-12-14 14:40:48'),(36,'发送邮件','NULL','/mg/v2/notifications/mail/','POST','NULL','0','2018-12-27 13:11:20','2018-12-27 13:11:20'),(37,'获取前端权限','NULL','/accounts/authorization/','GET','NULL','0','2018-12-27 16:28:07','2018-12-27 16:28:07'),(38,'获取镜像仓库信息','NULL','/task/v2/task_other/docker_registry/','GET','NULL','0','2019-01-14 16:12:58','2019-01-14 16:12:58'),(39,'已发布配置获取','NULL','/kerrigan/v1/conf/publish/','GET','NULL','0','2019-01-29 16:01:36','2019-01-29 16:01:36'),(40,'钩子提交任务','NULL','/task/v2/task/accept/','POST','NULL','0','2019-03-18 16:49:01','2019-03-18 16:48:48'),(42,'获取订单','NULL','/task/v2/task/list/','GET','NULL','0','2019-03-21 10:55:51','2019-03-21 10:55:51'),(43,'超管注册用户','NULL','/mg/register/','POST','NULL','0','2019-03-21 11:08:50','2019-03-21 11:05:28'),(44,'超管重置MFA','NULL','/mg/v2/accounts/reset_mfa/','PUT','NULL','0','2019-03-21 11:09:42','2019-03-21 11:09:42'),(45,'超管重置用户密码','NULL','/mg/v2/accounts/reset_pw/','PUT','NULL','0','2019-03-21 11:10:18','2019-03-21 11:10:18'),(46,'查看系统配置','NULL','/mg/v2/sysconfig/settings/','GET','NULL','0','2019-03-21 11:11:32','2019-03-21 11:11:32'),(47,'修改系统配置','NULL','/mg/v2/sysconfig/settings/','POST','NULL','0','2019-03-21 11:12:09','2019-03-21 11:12:09'),(48,'测试邮件和短信','NULL','/mg//v2/sysconfig/check/','POST','NULL','0','2019-03-21 11:12:40','2019-03-21 11:12:40'),(49,'用户管理所有权限','NULL','/mg//v2/accounts/','ALL','NULL','0','2019-03-21 11:13:43','2019-03-21 11:13:43'),(50,'发送短信API','NULL','/mg/v2/notifications/sms/','POST','NULL','0','2019-03-21 11:15:19','2019-03-21 11:15:19'),(51,'发送邮件API','NULL','/mg/v2/notifications/mail/','POST','NULL','0','2019-03-21 11:15:46','2019-03-21 11:15:46'),(52,'配置中心所有权限-项目 要单独赋权','NULL','/kerrigan/v1/conf/','ALL','NULL','0','2019-03-21 11:40:13','2019-03-21 11:40:13'),(53,'调 度任务日志','NULL','/task/ws/v1/task/log/','ALL','NULL','0','2019-04-12 09:22:39','2019-03-21 11:41:51'),(54,'查看任务详情','NULL','/task/v2/task/check/','GET','NULL','0','2019-03-21 11:47:15','2019-03-21 11:47:15'),(55,'查看历史任务','NULL','/task/v2/task/check_history/','GET','NULL','0','2019-03-21 12:09:43','2019-03-21 11:51:44'),(56,'干预调度任务','NULL','/task/v2/task/check/','PUT','NULL','0','2019-03-21 12:00:17','2019-03-21 11:54:50'),(57,'调度任务重做-终止','NULL','/task/v2/task/check/','PATCH','NULL','0','2019-04-25 18:00:54','2019-03-21 11:55:35'),(59,'调度任务模板','NULL','/task/v2/task_layout/','ALL','NULL','0','2019-03-21 11:57:36','2019-03-21 11:57:36'),(60,'调度任务全部终止','NULL','/task/v2/task/list/','PUT','NULL','0','2019-03-21 12:00:39','2019-03-21 12:00:39'),(61,'资产管理查看主机','NULL','/cmdb/v1/cmdb/server/','GET','NULL','0','2019-03-21 12:19:58','2019-03-21 12:05:00'),(62,'资产管理-查看主机组','NULL','/cmdb/v1/cmdb/server_group/','GET','NULL','0','2019-03-21 12:20:04','2019-03-21 12:05:18'),(63,'资产管理-查看审计日志','NULL','/cmdb/v1/cmdb/server_log/','GET','NULL','0','2019-03-21 12:20:08','2019-03-21 12:05:38'),(64,'数据库优化日志','NULL','/task/ws/v1/task/log_data/','ALL','NULL','0','2019-04-12 09:23:27','2019-04-12 09:23:27'),(65,'页面任务发布','NULL','/task//other/v1/submission/','ALL','NULL','0','2019-04-12 09:24:36','2019-04-12 09:24:36'),(66,'任务提交-发布','NULL','/task/other/v1/submission/publish/','ALL','NULL','0','2019-04-12 09:25:06','2019-04-12 09:25:06'),(67,'任务提交-数据库 审计','NULL','/task/other/v1/submission/mysql_audit/','ALL','NULL','0','2019-04-12 09:25:55','2019-04-12 09:25:55'),(68,'任务提交-数据库优化','NULL','/task/other/v1/submission/mysql_opt/','ALL','NULL','0','2019-04-12 09:26:24','2019-04-12 09:26:24'),(69,'任务提交-自定义','NULL','/task/other/v1/submission/custom_task/','ALL','NULL','0','2019-04-12 09:26:54','2019-04-12 09:26:54'),(70,'任务提交-自定义-代理','NULL','/task/other/v1/submission/custom_task_proxy/','ALL','NULL','0','2019-04-12 09:27:49','2019-04-12 09:27:49'),(71,'任务提交-自定义-json','NULL','/task/other/v1/submission/post_task/','ALL','NULL','0','2019-04-12 09:28:18','2019-04-12 09:28:18'),(72,'获取有权限资产标签','NULL','/task/other/v1/record/tag_auth/','GET','NULL','0','2019-04-15 10:33:37','2019-04-15 10:33:37'),(73,'订单审批','NULL','/task/v2/task/list/','PATCH','NULL','0','2019-04-25 17:27:20','2019-04-25 17:27:20'),(74,'PrometheusWebHooks','NULL','/tools/v1/tools/send/prometheus/','POST','NULL','0','2019-04-26 17:30:10','2019-04-26 17:30:10'),(75,'任务统计','NULL','/task/v2/task/statement/','GET','NULL','0','2019-05-21 10:58:25','2019-05-21 10:58:25'),(76,'DNS页面所有权限','NULL','/dns/v1/dns/bind/','ALL','NULL','0','2019-05-23 09:17:17','2019-05-23 09:17:17'),(77,'DNS查看域名','NULL','/dns/v1/dns/bind/domain/','GET','NULL','0','2019-05-23 09:17:55','2019-05-23 09:17:55'),(78,'DNS添加域名','NULL','/dns/v1/dns/bind/domain/','POST','NULL','0','2019-05-23 09:18:20','2019-05-23 09:18:20'),(79,'DNS删除域名','NULL','/dns/v1/dns/bind/domain/','DELETE','NULL','0','2019-05-23 09:18:48','2019-05-23 09:18:48'),(80,'DNS域名禁用启用','NULL','/dns/v1/dns/bind/domain/','PATCH','NULL','0','2019-05-23 09:19:10','2019-05-23 09:19:10'),(81,'DNS-API脚本获取域名','NULL','/dns/v2/dns/bind/domain/','GET','NULL','0','2019-05-23 09:20:04','2019-05-23 09:20:04'),(82,'DNS-API脚本获取区域','NULL','/dns/v2/dns/bind/zone/','GET','NULL','0','2019-05-23 09:20:39','2019-05-23 09:20:39'),(83,'DNS-区域文件所有权 限','NULL','/dns/v1/dns/bind/zone/','ALL','NULL','0','2019-05-23 09:21:23','2019-05-23 09:21:23'),(84,'DNS-添 加解析','NULL','/dns/v1/dns/bind/zone/','POST','NULL','0','2019-05-23 09:21:58','2019-05-23 09:21:58'),(85,'DNS-查看解析','NULL','/dns/v1/dns/bind/zone/','GET','NULL','0','2019-05-23 09:22:39','2019-05-23 09:22:39'),(86,'DNS-删除解析','NULL','/dns/v1/dns/bind/zone/','DELETE','NULL','0','2019-05-23 09:23:02','2019-05-23 09:23:02'),(87,'DNS-修改解析','NULL','/dns/v1/dns/bind/zone/','PUT','NULL','0','2019-05-23 09:23:38','2019-05-23 09:23:38'),(88,'DNS-解析禁用启用','NULL','/dns/v1/dns/bind/zone/','PATCH','NULL','0','2019-05-23 09:24:09','2019-05-23 09:24:09'),(89,'DNS-获取配置','NULL','/dns/v1/dns/bind/conf/','GET','NULL','0','2019-05-23 09:24:57','2019-05-23 09:24:57'),(90,'DNS-查看日志','NULL','/dns/v1/dns/bind/log/','GET','NULL','0','2019-05-23 09:25:31','2019-05-23 09:25:31'),(91,'CMDB-获取主机','NULL','/cmdb2//v1/cmdb/server/','GET','NULL','0','2019-05-23 10:02:48','2019-05-23 10:02:48'),(92,'CMDB-添加主机','NULL','/cmdb2/v1/cmdb/server/','POST','NULL','0','2019-05-23 10:16:29','2019-05-23 10:16:29'),(93,'CMDB-更新主机','NULL','/cmdb2/v1/cmdb/server/','PUT','NULL','0','2019-05-23 10:16:57','2019-05-23 10:16:57'),(94,'CMDB-删除主机','NULL','/cmdb2/v1/cmdb/server/','DELETE','NULL','0','2019-05-23 10:17:18','2019-05-23 10:17:18'),(95,'CMDB-查看主机详情','NULL','/cmdb2/v1/cmdb/server_detail/','GET','NULL','0','2019-05-23 10:22:24','2019-05-23 10:22:24'),(96,'CMDB-获取DB','NULL','/cmdb2/v1/cmdb/db/','GET','NULL','0','2019-05-23 10:24:11','2019-05-23 10:24:11'),(97,'CMDB-添加DB','NULL','/cmdb2/v1/cmdb/db/','POST','NULL','0','2019-05-23 10:24:22','2019-05-23 10:24:22'),(98,'CMDB-更新DB','NULL','/cmdb2/v1/cmdb/db/','PUT','NULL','0','2019-05-23 10:24:46','2019-05-23 10:24:46'),(99,'CMDB-删除DB','NULL','/cmdb2/v1/cmdb/db/','DELETE','NULL','0','2019-05-23 10:25:02','2019-05-23 10:25:02'),(100,'CMDB-获取标签','NULL','/cmdb2/v1/cmdb/tag/','GET','NULL','0','2019-05-23 10:25:46','2019-05-23 10:25:46'),(101,'CMDB-添加标签','NULL','/cmdb2/v1/cmdb/tag/','POST','NULL','0','2019-05-23 10:26:21','2019-05-23 10:26:15'),(102,'CMDB-更新标签','NULL','/cmdb2/v1/cmdb/tag/','PUT','NULL','0','2019-05-23 10:26:42','2019-05-23 10:26:42'),(103,'CMDB-删除标签','NULL','/cmdb2/v1/cmdb/tag/','DELETE','NULL','0','2019-05-23 10:26:54','2019-05-23 10:26:54'),(104,'CMDB-主机资产更新','NULL','/cmdb2//v1/cmdb/server/asset_update/','POST','NULL','0','2019-05-23 10:27:35','2019-05-23 10:27:35'),(105,'CMDB-获取资产配置','NULL','/cmdb2/v1/cmdb/asset_configs/','GET','NULL','0','2019-05-23 10:28:14','2019-05-23 10:28:14'),(106,'CMDB-添加资产配置','NULL','/cmdb2/v1/cmdb/asset_configs/','POST','NULL','0','2019-05-23 10:28:27','2019-05-23 10:28:27'),(107,'CMDB-更新资产配置','NULL','/cmdb2/v1/cmdb/asset_configs/','PUT','NULL','0','2019-05-23 10:28:39','2019-05-23 10:28:39'),(108,'CMDB-删除资产配置','NULL','/cmdb2/v1/cmdb/asset_configs/','DELETE','NULL','0','2019-05-23 10:28:56','2019-05-23 10:28:56'),(109,'CMDB-拉取云厂商主机信息','NULL','/cmdb2//v1/cmdb/asset_configs/handler_update_server/','GET','NULL','0','2019-05-23 11:02:32','2019-05-23 11:02:32');`

**Comment by fairychao** [comment]
新增的两个字段app_code和parameters都设置为null，或者删除这两个字段，都可以；建议设置为null

**Comment by fairychao** [comment]
已处理
